---
- name: Waiting for Zookeeper port | "{{ PortNumber }}" | to be | "{{ PortStatus }}"
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ PortNumber }}"
    state: "{{ PortStatus }}"
    timeout: 300
    delay: 10
