---

- name: Creating Service File | Kafka
  template:
    src: service.j2
    dest: /usr/lib/systemd/system/kafka.service

- name: Creating Service File | zookeeper | RedHat
  template:
    src: service_zookeeper.j2
    dest: /usr/lib/systemd/system/zookeeper.service
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'RedHat'] | list

- name: Creating Service File | zookeeper | Debian/Ubuntu
  template:
    src: service_zookeeper.j2
    dest: /lib/systemd/system/zookeeper.service
  when: ansible_distribution in ['Debian', 'Ubuntu'] | list
