---

- name: Creating symlink to latest version | {{ kafkaVersion }}
  file:
    src: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}"
    dest: "{{ kafkaInstallDir }}/kafka"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    state: link
  register: kafkaSymlinkStatus

- name: Creating symlink to latest version | {{ zookeeperVersion }}
  file:
    src: "{{ zookeeperInstallDir }}/zookeeper-{{ zookeeperVersion }}"
    dest: "{{ zookeeperInstallDir }}/zookeeper"
    owner: "{{ zookeeperUser }}"
    group: "{{ zookeeperGroup }}"
    state: link
  register: zookeeperSymlinkStatus
